[package]
name = "ccx"
version = "0.1.0"
authors = ["Alexander Irbis <irbis.labs@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "api/binance",
]

[dependencies]
ccx-binance = { path = "api/binance" }
