[package]
name = "ccx"
version = "0.1.0"
authors = ["Alexander Irbis <irbis.labs@gmail.com>"]
edition = "2018"
resolver = "2"

[workspace]
members = [
    "api/binance",
    "api/binance/examples/util",
    "api/kraken",
    "api/kraken/examples/util",
    "util/lib",
]

[dependencies]
ccx-binance = { path = "api/binance" }
ccx-kraken = { path = "api/kraken" }
